name: file-manager
services:
  backend:
    image: file-manager:latest
    depends_on:
      - database
      - minio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_AUD=$JWT_AUD
      - JWT_ISS=$JWT_ISS
      - BASE_APP_URL=$BASE_APP_URL
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
      - MINIO_BUCKET=$MINIO_BUCKET
      - MINIO_USE_SSL=$MINIO_USE_SSL
      - MINIO_PORT=$MINIO_PORT
      - ALLOWED_ORIGINS=$ALLOWED_ORIGINS
      - ALLOWED_WILDCARD_DOMAINS=$ALLOWED_WILDCARD_DOMAINS
      - EMAIL_PROVIDER=$EMAIL_PROVIDER
      - EMAIL_FROM=$EMAIL_FROM
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - DB_URL=$DB_URL
      - MINIO_ENDPOINT=$MINIO_ENDPOINT
      - BASE_API_DOMAIN=$BASE_API_DOMAIN
      - ONLYOFFICE_URL=$ONLYOFFICE_URL
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.rule=HostRegexp(`^.+\.api\.docma\.yilmer\.com$`)
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.entryPoints=https
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.middlewares=gzip
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.service=https-0-bkok88skg80kc4c0kggc8oww
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.tls.certresolver=letsencrypt
      - traefik.http.services.https-0-bkok88skg80kc4c0kggc8oww.loadbalancer.server.port=3000
      - traefik.http.routers.https-0-bkok88skg80kc4c0kggc8oww.tls=true
      - traefik.http.routers.http-0-bkok88skg80kc4c0kggc8oww.rule=HostRegexp(`^.+\.api\.docma\.yilmer\.com$`)
      - traefik.http.routers.http-0-bkok88skg80kc4c0kggc8oww.entryPoints=http
      - traefik.http.routers.http-0-bkok88skg80kc4c0kggc8oww.middlewares=redirect-to-https
      - caddy_0.encode=zstd gzip
      - caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}
      - caddy_0.handle_path=*
      - caddy_0.header=-Server
      - caddy_0.try_files={path} /index.html /index.php
      - caddy_0=://
      - caddy_ingress_network=coolify
  migrate:
    image: file-manager:latest
    command:
      - "start:migrate"
    depends_on:
      - database
      - backend
    environment:
      DB_URL: $DB_URL
  seed:
    image: file-manager:latest
    command:
      - "start:seed"
    depends_on:
      - migrate
      - backend
    environment:
      DB_URL: $DB_URL
  database:
    image: 'postgres:16.8-alpine'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    entrypoint:
      - "sh"
      - "-c"
      - |
        echo 'patching https://github.com/ONLYOFFICE/DocumentServer/issues/2186...'
        find /var/www/onlyoffice/documentserver -name sdk-all-min.js -exec sed -E -i 's|(function +\w+\(\w+\) *\{ *function +\w+\(\)) *\{ *(\w+)\.open\((\w+),(\w+),(\w+)\);|\1{\nif (\4 \&\& \4.length > 5) {if (\4.substring(0, 5) == "http:") {\4 = \4.replace("http://", "https://");}};\n\2.open(\3,\4,\5);\n|' '{}' ';'
        echo 'done! starting server...'
        /app/ds/run-document-server.sh
    environment:
      - JWT_SECRET=$JWT_SECRET
      - JWT_ENABLED=$JWT_ENABLED
    volumes:
      - 'onlyoffice_logs:/var/log/onlyoffice'
      - 'onlyoffice_data:/var/www/onlyoffice/Data'
      - 'onlyoffice_lib:/var/lib/onlyoffice'
      - 'onlyoffice_db:/var/lib/postgresql'
      - './onlyoffice/documentserver/default.json:/etc/onlyoffice/documentserver/default.json'
#      - './onlyoffice/certs/:/var/www/onlyoffice/Data/certs/'
