name: file-manager
services:
  backend:
    container_name: "file-manager"
    image: file-manager:latest
    depends_on:
      - database
      - minio
      - onlyoffice
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: $DB_PORT
      DB_SCHEMA: $DB_SCHEMA
      PORT: $PORT
      JWT_SECRET: $JWT_SECRET
      JWT_AUD: $JWT_AUD
      JWT_ISS: $JWT_ISS
      BASE_APP_URL: $BASE_APP_URL
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_BUCKET: $MINIO_BUCKET
      MINIO_USE_SSL: $MINIO_USE_SSL
      MINIO_PORT: $MINIO_PORT
      ALLOWED_ORIGINS: $ALLOWED_ORIGINS
      ALLOWED_WILDCARD_DOMAINS: $ALLOWED_WILDCARD_DOMAINS
      EMAIL_PROVIDER: $EMAIL_PROVIDER
      EMAIL_FROM: $EMAIL_FROM
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      DB_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_DATABASE}"
      MINIO_ENDPOINT: "minio"
      PROTOCOL: "http"
      BASE_API_DOMAIN: "backend:3000"      
      ONLYOFFICE_URL: http://onlyoffice
    ports:
      - "$PORT:$PORT"
  migrate:
    container_name: "file-manager-migrate"
    image: file-manager:latest
    command:
      - "start:migrate"
    depends_on:
      - database
      - backend
    environment:
      DB_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@database:${DB_PORT}/${DB_DATABASE}"
  database:
    container_name: database
    image: postgres:16.8-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_SCHEMA: ${DB_SCHEMA}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    environment:
      JWT_SECRET: $JWT_SECRET
      JWT_ENABLED: false
      ONLYOFFICE_HTTPS_HSTS_ENABLED: false
    volumes:
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_lib:/var/lib/onlyoffice
      - onlyoffice_db:/var/lib/postgresql
    ports:
      - '80:80'
volumes:
  database_data:
  minio_data:
  onlyoffice_logs:
  onlyoffice_data:
  onlyoffice_lib:
  onlyoffice_db:
