name: file-manager
services:
  backend:
    container_name: "file-manager"
    image: file-manager:latest
    depends_on:
      - database
      - minio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: $DB_PORT
      DB_SCHEMA: $DB_SCHEMA
      PORT: $PORT
      JWT_SECRET: $JWT_SECRET
      JWT_AUD: $JWT_AUD
      JWT_ISS: $JWT_ISS
      BASE_APP_URL: $BASE_APP_URL
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
      MINIO_BUCKET: $MINIO_BUCKET
      MINIO_USE_SSL: $MINIO_USE_SSL
      MINIO_PORT: $MINIO_PORT
      ALLOWED_ORIGINS: $ALLOWED_ORIGINS
      ALLOWED_WILDCARD_DOMAINS: $ALLOWED_WILDCARD_DOMAINS
      EMAIL_PROVIDER: $EMAIL_PROVIDER
      EMAIL_FROM: $EMAIL_FROM
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION
      DB_URL: $DB_URL
      MINIO_ENDPOINT: $MINIO_ENDPOINT
  migrate:
    container_name: "file-manager-migrate"
    image: file-manager:latest
    command:
      - "start:migrate"
    depends_on:
      - database
      - backend
    environment:
      DB_URL: $DB_URL
  database:
    container_name: database
    image: postgres:16.8-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_SCHEMA: ${DB_SCHEMA}
    volumes:
      - database_data:/var/lib/postgresql
  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: $MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $MINIO_SECRET_KEY
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  database_data:
  minio_data:
